---
- name: Create pxe user
  user: name={{ pxe_user }} comment="pxe" shell=/bin/bash

- name: Clone pxe repo
  git: repo=https://github.com/pxe/tftpboot.git dest={{ pxe_path }} version=1.2
  become_user: "{{ pxe_user }}"

- name: Install systemd unit
  template: src=pxe.service.j2 dest=/etc/systemd/system/pxe.service

- name: Enable pxe service
  # Manually, see ansible-modules-core #3784
  systemd: enabled=True name=pxe
  notify:
  - Restart pxe
