---
- name: Create erpxe user
  user: name={{ erpxe_user }} comment="erpxe" shell=/bin/bash

- name: Clone erpxe repo
  git: repo=https://github.com/ERPXE/tftpboot.git dest={{ erpxe_path }} version=1.2
  become_user: "{{ erpxe_user }}"

- name: Install systemd unit
  template: src=erpxe.service.j2 dest=/etc/systemd/system/erpxe.service

- name: Enable erpxe service
  # Manually, see ansible-modules-core #3784
  systemd: enabled=True name=erpxe
  notify:
  - Restart erpxe
