---
- name: Install Packages (neither debian nor ubuntu)
  package:
    name: syslinux
    state: latest
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Check if syslinux files copied
  stat:
    path: "{{ pxe_root_path }}/pxelinux.0"
  register: stat_result

- name: Download and extract debian netboot
  unarchive:
    src: http://debian.gtisc.gatech.edu/debian/dists/stable/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: "{{ pxe_root_path }}"
    remote_src: True
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy syslinux files to root
  shell: cp -r /usr/share/syslinux/* "{{ pxe_root_path }}"
  when: stat_result.stat.exists == False and ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: Check if cfg directory exists
  stat:
    path: "{{ pxe_root_path }}/pxelinux.cfg"
  register: stat_result_cfg

- name: Create cfg directory
  file:
    path: "{{ pxe_root_path }}/pxelinux.cfg"
    state: directory
    mode: 0755

- name: Copy config
  template:
    src: default.j2
    dest: "{{ pxe_root_path }}/pxelinux.cfg/{{ pxe_config_name }}"

- include: populate.yml
  vars:
    path: "{{ pxe_images_path }}/{{ item.name }}/{{ item.arch }}"
  with_items:
    - "{{ pxe_images }}"
