---
- name: Install Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - tftp-server
    - syslinux

- name: Systemd enable tftp
  systemd:
    name: tftp
    enabled: yes
    state: started

- name: TFTP firewall rule
  firewalld:
    port: 69/udp
    permanent: true
    state: enabled

- name: Check if syslinux files copied
  stat:
    path: "/var/lib/tftpboot/pxelinux.0"
  register: stat_result

- name: Copy syslinux files to root
  shell: cp -r /usr/share/syslinux/* /var/lib/tftpboot/
  when: stat_result.stat.exists == False

- name: Check if cfg directory exists
  stat:
    path: "{{ pxe_root_path }}/pxelinux.cfg"
  register: stat_result_cfg

- name: Create cfg directory
  file:
    path: "{{ pxe_root_path }}/pxelinux.cfg"
    state: directory
    mode: 0755

- name: Copy config
  template:
    src: default.j2
    dest: "{{ pxe_root_path }}/pxelinux.cfg/default"

- include: populate.yml
  vars:
    url: "{{ item.url }}"
    path: "{{ pxe_images_path }}/{{ item.name }}/{{ item.arch }}"
  with_items:
    - "{{ pxe_images }}"
