---
- name: Create pxe user
  user: name={{ pxe_user }} comment="pxe" shell=/bin/bash

- name: Install the latest version of unzip
  package:
    name: unzip
    state: latest

- name: Check if downloaded
  stat:
    path: "{{ pxe_path }}/fogproject-{{ pxe_version }}"
  register: stat_result

- name: Download and extract fog archive
  unarchive:
    src: "https://github.com/FOGProject/fogproject/archive/{{ pxe_version }}.zip"
    dest: "{{ pxe_path }}"
    remote_src: True
  become_user: "{{ pxe_user }}"
  when: stat_result.stat.exists == False
