---
- name: Create directory
  file:
    path: "{{ path }}"
    state: directory
    mode: 0755

- name: Download initrd
  get_url:
    url: "{{ item.url }}/{{ item.initrd }}"
    dest: "{{ path }}/{{ item.initrd }}"
    mode: 0664

- name: Download vmlinuz
  get_url:
    url: "{{ item.url }}/{{ item.kernel }}"
    dest: "{{ path }}/{{ item.kernel }}"
    mode: 0664
