---
- name: Create directory
  file:
    path: "{{ path }}"
    state: directory
    mode: 0755

- name: Check for initrd
  stat:
    path: "{{ path }}/initrd.img"
  register: stat_result_initrd

- name: download initrd
  get_url:
    url: "{{ url }}/initrd.img"
    dest: "{{ path }}/initrd.img"
    mode: 0664
  when: stat_result_initrd.stat.exists == False

- name: Check for vmlinuz
  stat:
    path: "{{ path }}/vmlinuz"
  register: stat_result_vmlinuz

- name: download vmlinuz
  get_url:
    url: "{{ url }}/vmlinuz"
    dest: "{{ path }}/vmlinuz"
    mode: 0664
  when: stat_result_vmlinuz.stat.exists == False
